version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rayan
      MYSQL_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: