- name: Setup Laravel with Docker
  hosts: web
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT package index after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Clone latest app
      git:
        repo: 'https://github.com/sudo38/laravel-deploy-to-ec2.git'
        dest: /home/ubuntu/laravel
        version: main
        force: yes

    - name: Copy .env file
      copy:
        src: ../.env.example
        dest: /home/ubuntu/laravel/.env

    - name: Build Docker image
      command: docker compose build
      args:
        chdir: /home/ubuntu/laravel

    - name: Run Docker container
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/laravel
