name: Build and Deploy using Artifacts

on:
  workflow_dispatch

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js (example)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          mkdir -p build
          echo "This is the build output" > build/output.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./deployed-build

      - name: Display Artifact Contents
        run: |
          echo "Listing contents of downloaded artifact:"
          ls -R ./deployed-build

      # Simulate deployment
      - name: Deploy (simulation)
        run: echo "Deploying application from ./deployed-build/output.txt"
