name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via Ansible
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
        chmod 400 ~/.ssh/key.pem

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      run: |
        sudo apt update
        sudo apt install -y ansible
        ansible-playbook -i "${{ secrets.EC2_HOST }}," ansible/main.yml \
          --user ubuntu \
          --private-key ~/.ssh/key.pem
